### ISSUE TITLE
BINANCE - Create Market Data Endpoint request and response objects

### ISSUE THREAD

**Issue by zeeveener** [zeeveener/Crypto-Exchange-APIs#29]
As defined [Here](https://www.binance.com/restapipub.html#user-content-market-data-endpoints)

- [ ] Get Order Book
- [ ] Get Aggregate Trades
- [ ] Get Klines
- [ ] Get 24hr price ticker
- [ ] Get symbols current price ticker
- [ ] Get symbols order book ticker
